### ISSUE TITLE
get 'Client sent an HTTP request to an HTTPS server' error. reverse proxy portainer

### ISSUE THREAD

**Issue by neozhu** [JamesTurland/JimsGarage#130]
```yaml
http:
  middlewares:    
    default-security-headers:
      headers:
        customBrowserXSSValue: 0                          # X-XSS-Protection=1; mode=block
        contentTypeNosniff: true                          # X-Content-Type-Options=nosniff
        forceSTSHeader: true                              # Add the Strict-Transport-Security header even when the connection is HTTP
        frameDeny: false                                   # X-Frame-Options=deny
        referrerPolicy: "strict-origin-when-cross-origin"
        stsIncludeSubdomains: true                        # Add includeSubdomains to the Strict-Transport-Security header
        stsPreload: true                                  # Add preload flag appended to the Strict-Transport-Security header
        stsSeconds: 3153600                              # Set the max-age of the Strict-Transport-Security header (63072000 = 2 years)
        contentSecurityPolicy: "default-src 'self'"     
        customRequestHeaders:
          X-Forwarded-Proto: https
    https-redirectscheme:
      redirectScheme:
        scheme: https
        permanent: true

  routers:
    portainer:
      entryPoints:
        - "https"
      rule: "Host(`portainer.blazors.app`)"
      middlewares:
        - default-security-headers
        - https-redirectscheme
      tls: {}
      service: portainer
    edge:
      entryPoints:
        - "https"
      rule: "Host(`edge.blazors.app`)"
      middlewares:
        - default-security-headers
        - https-redirectscheme
      service: edge
      tls: {}
  services:
    portainer:
      loadBalancer:
        servers:
          - url: "https://10.33.1.166:9443"
        passHostHeader: true
    edge:
      loadBalancer:
        servers:
          - url: "https://10.33.1.166:8000"
        passHostHeader: true
```

I've tried both [https://10.33.1.166:9443/](https://10.33.1.166:9443) and [http://10.33.1.166:9000/](http://10.33.1.166:9000) locally, and they both work fine. But when accessing through the reverse proxy, it doesn't work. I'm not sure why.

**Comment by krod1408** [comment]
Try this it removes the redirect loop from the HTTPS routers, fixes the security header values to match your comments, and cleans up the manual header overrides.

```
http:
  middlewares:    
    default-security-headers:
      headers:
        # Standard XSS protection (1; mode=block)
        browserXssFilter: true                            
        contentTypeNosniff: true                          
        # Recommended to serve HSTS only over HTTPS
        forceSTSHeader: false                              
        # Protects against clickjacking
        frameDeny: true                                   
        referrerPolicy: "strict-origin-when-cross-origin"
        stsIncludeSubdomains: true                        
        stsPreload: true                                  
        # Updated to 2 years (63072000 seconds) as per your comment
        stsSeconds: 63072000                              
        contentSecurityPolicy: "default-src 'self'"     
        # Removed X-Forwarded-Proto as Traefik handles this automatically

    https-redirectscheme:
      redirectScheme:
        scheme: https
        permanent: true

  routers:
    # HTTP to HTTPS Redirect Router
    # This catches all HTTP traffic and moves it to HTTPS
    http-catchall:
      entryPoints:
        - "http"
      rule: "HostRegexp(`{host:.+}`)"
      middlewares:
        - https-redirectscheme
      service: noop@internal

    portainer:
      entryPoints:
        - "https"
      rule: "Host(`portainer.blazors.app`)"
      middlewares:
        - default-security-headers
      tls: {}
      service: portainer

    edge:
      entryPoints:
        - "https"
      rule: "Host(`edge.blazors.app`)"
      middlewares:
        - default-security-headers
      service: edge
      tls: {}

  services:
    portainer:
      loadBalancer:
        servers:
          - url: "https://10.33.1.166:9443"
        passHostHeader: true
    edge:
      loadBalancer:
        servers:
          - url: "https://10.33.1.166:8000"
        passHostHeader: true

# In your STATIC config (traefik.yml)
serversTransport:
  insecureSkipVerify: true

```
