### ISSUE TITLE
headscale config file not matching version

### ISSUE THREAD

**Issue by fabianmuehlberger** [JamesTurland/JimsGarage#65]
Hi,

While setting up Headscale, I noticed that the Headscale developers deliberately not use *latest* tag. 

Since the config.yaml has specific settings related to the version, this leads to a not working docker container. 

Their current recommendation for the [container deployment](https://github.com/juanfont/headscale/blob/v0.23.0-alpha5/docs/running-headscale-container.md) is: v0.23.0-alpha5

They additionally changed:
`command: headscale serve` to `command: server` and the volume mounts.
```
version: "3.9"
services:
  headscale:
    container_name: headscale
    image: headscale/headscale:0.23.0-alpha5
    restart: unless-stopped
    command: serve
    volumes:
      - ./config:/etc/headscale
      - /lib:/var/lib/headscale
      - /run:/var/run/headscale
```
The config.yaml should be pulled from the documentation with the correct tag.
